### ISSUE TITLE
config option for mac adress

### ISSUE THREAD

**Issue by utf18** [jsimonetti/btlocker#1]
Hey there,

for the config option do you prefer an env variable or a config file?

**Comment by jsimonetti** [comment]
Hi,

Preferably I would like it to support both. But my first preference would be config file (something in ~/.config/)
But, any way to do configuration is better than what we have now :)

**Comment by utf18** [comment]
hey, 
great work i forgot to mention that ;)

Do you have a strong opinion on the config way to do this either via cobra/viper or just with flags or just check the file it is not there then set some defaults.

**Comment by jsimonetti** [comment]
I have no strong oppinion about how to do this. But for such a simple program such as this, doing a complete 12-factor seems overkill.
That being said, I don't mind depending on viper/cobra, but if there is a way to keep this simple and lean, that would seem more appropriate

So perhaps use a ~/.config/btlocker/config.json file with a simple direct Struct to Json mapping would be ideal as this does not use external dependencies. If the file doesn't exist, use a fatal error (and `os.Exit(1)`).

It does not feel right to add a neighbor mac as a default. All the other config options are candidates for defaults. Where I want the unlockEnabled to default to false for security reasons.
